SET DEFINE OFF;
SET SERVEROUTPUT ON;

-- ==========================================
-- DROP TABLES
-- ==========================================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ALERTA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LEITURA_SATELITAL CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CULTURA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PROPRIEDADE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PRODUTOR CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE HISTORICO_CLIMA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ==========================================
-- PRODUTOR
-- ==========================================
CREATE TABLE PRODUTOR (
                          ID_PRODUTOR NUMBER GENERATED BY DEFAULT AS IDENTITY,
                          NOME VARCHAR2(100) NOT NULL,
                          CPF VARCHAR2(14) NOT NULL,
                          EMAIL VARCHAR2(100),
                          SENHA VARCHAR2(100),
                          TELEFONE VARCHAR2(20),
                          ESTADO VARCHAR2(2) NOT NULL,
                          CIDADE VARCHAR2(80) NOT NULL,
                          DT_CADASTRO DATE DEFAULT SYSDATE NOT NULL,
                          CONSTRAINT PK_PRODUTOR PRIMARY KEY (ID_PRODUTOR),
                          CONSTRAINT UK_PRODUTOR_CPF UNIQUE (CPF)
);

-- ==========================================
-- PROPRIEDADE
-- ==========================================
CREATE TABLE PROPRIEDADE (
                             ID_PROPRIEDADE NUMBER GENERATED BY DEFAULT AS IDENTITY,
                             ID_PRODUTOR NUMBER NOT NULL,
                             NOME_FAZENDA VARCHAR2(100) NOT NULL,
                             AREA_HECTARES NUMBER(10,2) NOT NULL,
                             LATITUDE NUMBER(10,6),
                             LONGITUDE NUMBER(10,6),
                             ESTADO VARCHAR2(2) NOT NULL,
                             MUNICIPIO VARCHAR2(80) NOT NULL,
                             DT_REGISTRO DATE DEFAULT SYSDATE NOT NULL,
                             CONSTRAINT PK_PROPRIEDADE PRIMARY KEY (ID_PROPRIEDADE),
                             CONSTRAINT FK_PROP_PRODUTOR FOREIGN KEY (ID_PRODUTOR) REFERENCES PRODUTOR(ID_PRODUTOR)
);

-- ==========================================
-- CULTURA
-- ==========================================
CREATE TABLE CULTURA (
                         ID_CULTURA NUMBER GENERATED BY DEFAULT AS IDENTITY,
                         ID_PROPRIEDADE NUMBER NOT NULL,
                         TIPO_CULTURA VARCHAR2(50) NOT NULL,
                         SAFRA VARCHAR2(10) NOT NULL,
                         AREA_PLANTADA NUMBER(10,2),
                         DT_PLANTIO DATE,
                         DT_COLHEITA_PREV DATE,
                         STATUS VARCHAR2(1) DEFAULT 'A' NOT NULL,
                         CONSTRAINT PK_CULTURA PRIMARY KEY (ID_CULTURA),
                         CONSTRAINT FK_CULTURA_PROPRIEDADE FOREIGN KEY (ID_PROPRIEDADE) REFERENCES PROPRIEDADE(ID_PROPRIEDADE)
);

-- ==========================================
-- LEITURA SATELITAL
-- ==========================================
CREATE TABLE LEITURA_SATELITAL (
                                   ID_LEITURA NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                   ID_PROPRIEDADE NUMBER NOT NULL,
                                   DT_LEITURA DATE NOT NULL,
                                   NDVI NUMBER(5,4),
                                   TEMPERATURA NUMBER(5,2),
                                   UMIDADE NUMBER(5,2),
                                   PRECIPITACAO NUMBER(6,2),
                                   FONTE_SATELITE VARCHAR2(30),
                                   CONSTRAINT PK_LEITURA PRIMARY KEY (ID_LEITURA),
                                   CONSTRAINT FK_LEITURA_PROPRIEDADE FOREIGN KEY (ID_PROPRIEDADE) REFERENCES PROPRIEDADE(ID_PROPRIEDADE)
);

-- ==========================================
-- ALERTA
-- ==========================================
CREATE TABLE ALERTA (
                        ID_ALERTA NUMBER GENERATED BY DEFAULT AS IDENTITY,
                        ID_PROPRIEDADE NUMBER NOT NULL,
                        ID_LEITURA NUMBER,
                        TIPO_ALERTA VARCHAR2(30) NOT NULL,
                        NIVEL_RISCO VARCHAR2(10) NOT NULL,
                        DESCRICAO VARCHAR2(200),
                        DT_ALERTA DATE DEFAULT SYSDATE NOT NULL,
                        RESOLVIDO VARCHAR2(1) DEFAULT 'N',
                        DT_RESOLUCAO DATE,
                        CONSTRAINT PK_ALERTA PRIMARY KEY (ID_ALERTA),
                        CONSTRAINT FK_ALERTA_PROPRIEDADE FOREIGN KEY (ID_PROPRIEDADE) REFERENCES PROPRIEDADE(ID_PROPRIEDADE),
                        CONSTRAINT FK_ALERTA_LEITURA FOREIGN KEY (ID_LEITURA) REFERENCES LEITURA_SATELITAL(ID_LEITURA)
);

-- ==========================================
-- HISTORICO CLIMA
-- ==========================================
CREATE TABLE HISTORICO_CLIMA (
                                 ID_CLIMA NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                 ESTADO VARCHAR2(2),
                                 MUNICIPIO VARCHAR2(80),
                                 ANO_MES VARCHAR2(7),
                                 TEMP_MEDIA NUMBER(5,2),
                                 TEMP_MAX NUMBER(5,2),
                                 TEMP_MIN NUMBER(5,2),
                                 PRECIPITACAO_MM NUMBER(8,2),
                                 UMIDADE_MEDIA NUMBER(5,2),
                                 CONSTRAINT PK_HISTORICO_CLIMA PRIMARY KEY (ID_CLIMA)
);

-- ==========================================
-- DADOS INICIAIS
-- ==========================================
INSERT INTO PRODUTOR (NOME, CPF, EMAIL, TELEFONE, ESTADO, CIDADE) VALUES ('Joao Alves','123','a@a.com','11999999999','SP','Sao Paulo');
INSERT INTO PROPRIEDADE (ID_PRODUTOR,NOME_FAZENDA,AREA_HECTARES,LATITUDE,LONGITUDE,ESTADO,MUNICIPIO) VALUES (1,'Fazenda Modelo',100,0,0,'SP','Sao Paulo');
INSERT INTO CULTURA (ID_PROPRIEDADE,TIPO_CULTURA,SAFRA,AREA_PLANTADA,DT_PLANTIO,DT_COLHEITA_PREV,STATUS) VALUES (1,'Soja','2025',100,SYSDATE,SYSDATE+120,'A');
INSERT INTO LEITURA_SATELITAL (ID_PROPRIEDADE,DT_LEITURA,NDVI,TEMPERATURA,UMIDADE,PRECIPITACAO,FONTE_SATELITE) VALUES (1,SYSDATE,0.65,28,70,12,'Sentinel');
INSERT INTO ALERTA (ID_PROPRIEDADE,ID_LEITURA,TIPO_ALERTA,NIVEL_RISCO,DESCRICAO) VALUES (1,1,'SECA','MEDIO','Monitorar irrigacao');
INSERT INTO HISTORICO_CLIMA (ESTADO,MUNICIPIO,ANO_MES,TEMP_MEDIA,TEMP_MAX,TEMP_MIN,PRECIPITACAO_MM,UMIDADE_MEDIA) VALUES ('SP','Sao Paulo','2025-05',25,31,18,120,65);

COMMIT;
EXIT;