// <auto-generated />
using System;
using AstroFarm.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace AstroFarm.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527015517_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AstroFarm.Api.Models.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ALERTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESCRICAO");

                    b.Property<DateTime>("DtAlerta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ALERTA");

                    b.Property<string>("NivelRisco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NIVEL_RISCO");

                    b.Property<int>("PropriedadeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PROPRIEDADE");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TIPO_ALERTA");

                    b.HasKey("Id");

                    b.HasIndex("PropriedadeId");

                    b.ToTable("ALERTA");
                });

            modelBuilder.Entity("AstroFarm.Api.Models.LeituraSatelital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LEITURA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DtLeitura")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_LEITURA");

                    b.Property<string>("FonteSatelite")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FONTE_SATELITE");

                    b.Property<double?>("Ndvi")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("NDVI");

                    b.Property<double?>("Precipitacao")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("PRECIPITACAO");

                    b.Property<int>("PropriedadeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PROPRIEDADE");

                    b.Property<double?>("Temperatura")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("TEMPERATURA");

                    b.Property<double?>("Umidade")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("UMIDADE");

                    b.HasKey("Id");

                    b.HasIndex("PropriedadeId");

                    b.ToTable("LEITURA_SATELITAL");
                });

            modelBuilder.Entity("AstroFarm.Api.Models.Produtor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PRODUTOR");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CIDADE");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CPF");

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CADASTRO");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ESTADO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME");

                    b.Property<string>("Telefone")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("Id");

                    b.ToTable("PRODUTOR");
                });

            modelBuilder.Entity("AstroFarm.Api.Models.Propriedade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PROPRIEDADE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AreaHectares")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("AREA_HECTARES");

                    b.Property<DateTime>("DtRegistro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_REGISTRO");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ESTADO");

                    b.Property<double?>("Latitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("LATITUDE");

                    b.Property<double?>("Longitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("LONGITUDE");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MUNICIPIO");

                    b.Property<string>("NomeFazenda")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME_FAZENDA");

                    b.Property<int>("ProdutorId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PRODUTOR");

                    b.HasKey("Id");

                    b.HasIndex("ProdutorId");

                    b.ToTable("PROPRIEDADE");
                });

            modelBuilder.Entity("AstroFarm.Api.Models.Alerta", b =>
                {
                    b.HasOne("AstroFarm.Api.Models.Propriedade", "Propriedade")
                        .WithMany()
                        .HasForeignKey("PropriedadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propriedade");
                });

            modelBuilder.Entity("AstroFarm.Api.Models.LeituraSatelital", b =>
                {
                    b.HasOne("AstroFarm.Api.Models.Propriedade", "Propriedade")
                        .WithMany()
                        .HasForeignKey("PropriedadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propriedade");
                });

            modelBuilder.Entity("AstroFarm.Api.Models.Propriedade", b =>
                {
                    b.HasOne("AstroFarm.Api.Models.Produtor", "Produtor")
                        .WithMany("Propriedades")
                        .HasForeignKey("ProdutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produtor");
                });

            modelBuilder.Entity("AstroFarm.Api.Models.Produtor", b =>
                {
                    b.Navigation("Propriedades");
                });
#pragma warning restore 612, 618
        }
    }
}
